name: Build & Push (all modules, consistent tag)

on:
  push:
    branches: [ main, develop, release/* ]
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # needed for GHCR; remove/adjust for Docker Hub
    env:
      REGISTRY: ghcr.io
      IMAGE_TAG: ${{ github.sha.substr(0,7) }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # Build the whole reactor so every module is compiled/tested on the same hash
      - name: Maven build (full reactor)
        run: mvn -B clean verify

      # Log in once (GHCR). For Docker Hub, replace registry/creds accordingly.
      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build & push BOTH images with the SAME tag (short SHA)
      - name: Build & push images (api, admin-portal)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: admin-portal/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/admin-portal:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & push API image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: api/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/api:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Also mark latest only for main branch
      - name: Tag latest (main only)
        if: github.ref == 'refs/heads/main'
        run: |
          docker pull $REGISTRY/${{ github.repository }}/admin-portal:${IMAGE_TAG}
          docker pull $REGISTRY/${{ github.repository }}/api:${IMAGE_TAG}
          docker tag $REGISTRY/${{ github.repository }}/admin-portal:${IMAGE_TAG} $REGISTRY/${{ github.repository }}/admin-portal:latest
          docker tag $REGISTRY/${{ github.repository }}/api:${IMAGE_TAG} $REGISTRY/${{ github.repository }}/api:latest
          docker push $REGISTRY/${{ github.repository }}/admin-portal:latest
          docker push $REGISTRY/${{ github.repository }}/api:latest
