name: CI (build & test - all modules)

on:
  push:
    branches: [ main, develop, release/* ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # Needed for Testcontainers (Docker daemon is available on GitHub-hosted runners)
      - name: Print Docker info
        run: docker info

      - name: Maven verify (unit + integration tests)
        run: mvn -B clean verify
